version: "3.1"
services:
  backend:
    container_name: quotes-pilot
    image: amitking2309/quotes-pilot:0.0.1-SNAPSHOT
    environment:
      - RDS_HOSTNAME=mysql
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - net
        
  frontend:
    container_name: quotes-pilot-frontend
    image: amitking2309/quotes-pilot-frontend:latest
    ports:
      - "3000:80"
    networks:
      - net  
    
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=quotedb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u sa -ppassword" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - net
networks:
  net:
    external:
      name: dedicated
