version: "3.1"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=quotedb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
